spring:
  application:
    name: ecommerce_service

  profiles:
    active: dev

  # Liquibase Configuration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true