spring:
  # Database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin@123
    url: jdbc:postgresql://ecommerce_postgres:5432/ecommerce_db?createDatabaseIfNotExist=true

# Logging Configuration
logging:
  level:
    com:
      example:
        ecommerce_service: WARN

# Application configuration
app:
  currency: BDT
